### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by desireB** [flytbase/flytsim-docker#1]
Hello,

I'm getting this error when I run : 
`
desire@desire-Oryx-Pro:~/Works/mapping/flytsim-docker/linux/nvidiagraphics$ sudo ./start.sh
`
I'm using Ubuntu 16.10 with a System76 laptop with 32GB of RAM and Nvidia GTX 1060 6GB of RAM

docker and nvidia-docker are working fine.

The trace is :  
`
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
`
`
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/nvidia-docker-compose", line 43, in <module>
    resp = request.urlopen('http://{0}/docker/cli/json'.format(args.nvidia_docker_host)).read().decode()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
ERROR: Problem encountered. Could not start Flytsim session
`

**Comment by sharvashish** [comment]
Hi @desireB ,

Sorry for delayed response. Was the problem resolved? If not please post your issue on forum at http://forums.flytbase.com/

**Comment by sharvashish** [comment]
Closing this issue, due to inactivity.
